# Ruff configuration
line-length = 88

[lint]
select = ["E", "F", "I", "N", "W", "B", "C4", "UP", "ARG", "PIE", "TCH", "Q", "SIM", "TID", "TCH", "RUF"]
ignore = ["E402", "E501"]  # Ignore "Module level import not at top of file" and "Line too long"
