line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "UP", "B", "Q", "W"]
ignore = [
  "E203",  # black-compat med slices
  "E501",  # line-too-long, handled by black
]

[format]
quote-style = "double"
indent-style = "space"
