# Ruff configuration
line-length = 88

[lint]
select = ["E", "F", "I", "N", "W", "B", "C4", "UP", "ARG", "PIE", "TCH", "Q", "SIM", "TID", "TCH", "RUF"]
ignore = ["E402", "E501", "ARG002", "SIM102", "SIM105", "SIM108", "SIM110", "SIM117", "PIE810", "RUF001", "RUF005", "RUF006", "RUF013", "TC001", "TC003", "C416"]  # Ignore common issues
