line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "UP", "B", "Q", "W"]
ignore = [
  "E203",  # black-compat med slices
  "E501",  # line-too-long, handled by black
]

[lint.per-file-ignores]
"src/codeconductor/app.py" = ["E402"]
"src/codeconductor/cli.py" = ["E402"]
"src/codeconductor/dashboard.py" = ["E402"]

[format]
quote-style = "double"
indent-style = "space"
