global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'codeconductor'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'codeconductor-health'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s 