"""
Export utilities for CodeConductor

This module provides functionality to export generated code, tests, and documentation
as downloadable files for users.
"""

import os
import zipfile
import tempfile
from datetime import datetime
from typing import Dict, Any, List, Optional
import json


class CodeExporter:
    """Export generated code and documentation as downloadable files."""

    def __init__(self, output_dir: str = "exports"):
        """Initialize the exporter with output directory."""
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def extract_code_from_agent_output(self, agent_output: str) -> Optional[str]:
        """Extract code blocks from agent output."""
        # Look for Python code blocks
        if "```python" in agent_output:
            start = agent_output.find("```python") + 9
            end = agent_output.find("```", start)
            if end != -1:
                return agent_output[start:end].strip()

        # Look for code blocks without language specifier
        if "```" in agent_output:
            start = agent_output.find("```") + 3
            end = agent_output.find("```", start)
            if end != -1:
                code = agent_output[start:end].strip()
                # Check if it looks like Python code
                if any(
                    keyword in code
                    for keyword in ["def ", "class ", "import ", "from "]
                ):
                    return code

        return None

    def extract_tests_from_agent_output(self, agent_output: str) -> Optional[str]:
        """Extract test code from TestAgent output."""
        # Look for test code blocks
        if "```python" in agent_output and (
            "test_" in agent_output or "pytest" in agent_output
        ):
            start = agent_output.find("```python") + 9
            end = agent_output.find("```", start)
            if end != -1:
                return agent_output[start:end].strip()

        return None

    def generate_requirements_txt(self, task_description: str) -> str:
        """Generate requirements.txt based on task description."""
        requirements = ["# Generated by CodeConductor\n"]

        # Add common dependencies based on task type
        if "api" in task_description.lower() or "rest" in task_description.lower():
            requirements.extend(
                ["fastapi>=0.68.0", "uvicorn>=0.15.0", "pydantic>=1.8.0"]
            )

        if "data" in task_description.lower() or "pandas" in task_description.lower():
            requirements.extend(["pandas>=1.3.0", "numpy>=1.21.0"])

        if "test" in task_description.lower() or "pytest" in task_description.lower():
            requirements.extend(["pytest>=6.0.0", "pytest-cov>=2.12.0"])

        # Always add common dependencies
        requirements.extend(["python-dotenv>=0.19.0", "requests>=2.25.0"])

        return "\n".join(requirements)

    def generate_readme_md(
        self, task_description: str, agent_outputs: Dict[str, Any]
    ) -> str:
        """Generate README.md with project documentation."""
        readme = f"""# {task_description.title()}

Generated by CodeConductor AI Assistant

## Overview

This project was automatically generated by CodeConductor's multi-agent AI system.

## Generated Components

"""

        # Add sections based on agent outputs
        if "ArchitectAgent" in agent_outputs:
            readme += "### Architecture\n"
            readme += "Designed by ArchitectAgent with focus on maintainability and scalability.\n\n"

        if "CodeGenAgent" in agent_outputs:
            readme += "### Implementation\n"
            readme += "Code generated by CodeGenAgent with comprehensive documentation and error handling.\n\n"

        if "ReviewAgent" in agent_outputs:
            readme += "### Code Quality\n"
            readme += "Reviewed by ReviewAgent for best practices and optimization opportunities.\n\n"

        if "PolicyAgent" in agent_outputs:
            readme += "### Security\n"
            readme += "Validated by PolicyAgent for security compliance and safety.\n\n"

        if "TestAgent" in agent_outputs:
            readme += "### Testing\n"
            readme += "Comprehensive test suite generated by TestAgent with edge cases and performance benchmarks.\n\n"

        readme += """## Installation

```bash
pip install -r requirements.txt
```

## Usage

```bash
python main.py
```

## Testing

```bash
pytest
```

## Generated by

CodeConductor - Educational AI Coding Assistant
https://github.com/yourusername/CodeConductor

---
*This code was generated with transparency and educational value in mind.*
"""

        return readme

    def create_export_zip(
        self, task_description: str, agent_outputs: Dict[str, Any]
    ) -> str:
        """Create a ZIP file with all generated code and documentation."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        task_name = task_description.replace(" ", "_").replace(":", "").lower()[:30]
        zip_filename = f"codeconductor_{task_name}_{timestamp}.zip"
        zip_path = os.path.join(self.output_dir, zip_filename)

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            # Extract and add main code
            if "CodeGenAgent" in agent_outputs:
                code = self.extract_code_from_agent_output(
                    agent_outputs["CodeGenAgent"]
                )
                if code:
                    zipf.writestr("main.py", code)

            # Extract and add tests
            if "TestAgent" in agent_outputs:
                tests = self.extract_tests_from_agent_output(agent_outputs["TestAgent"])
                if tests:
                    zipf.writestr("test_main.py", tests)

            # Generate and add requirements.txt
            requirements = self.generate_requirements_txt(task_description)
            zipf.writestr("requirements.txt", requirements)

            # Generate and add README.md
            readme = self.generate_readme_md(task_description, agent_outputs)
            zipf.writestr("README.md", readme)

            # Add agent discussion log
            discussion_log = self.create_discussion_log(task_description, agent_outputs)
            zipf.writestr("agent_discussion.md", discussion_log)

            # Add metadata
            metadata = {
                "task_description": task_description,
                "generated_at": datetime.now().isoformat(),
                "agents_used": list(agent_outputs.keys()),
                "codeconductor_version": "1.0.0",
            }
            zipf.writestr("metadata.json", json.dumps(metadata, indent=2))

        return zip_path

    def create_discussion_log(
        self, task_description: str, agent_outputs: Dict[str, Any]
    ) -> str:
        """Create a markdown file with the full agent discussion."""
        log = f"""# Agent Discussion: {task_description}

Generated by CodeConductor AI Assistant

## Task Description
{task_description}

## Agent Discussion

"""

        for agent_name, output in agent_outputs.items():
            log += f"### {agent_name}\n\n"
            log += f"{output}\n\n"
            log += "---\n\n"

        log += f"""
## Summary

This code was generated through a collaborative discussion between {len(agent_outputs)} AI agents:

"""

        for agent_name in agent_outputs.keys():
            log += f"- **{agent_name}**: {self.get_agent_description(agent_name)}\n"

        log += """
## Educational Value

This discussion demonstrates:
- How AI agents collaborate to solve complex problems
- The reasoning behind design decisions
- Best practices in software development
- Security considerations in code generation

---
*Generated with transparency and educational value in mind.*
"""

        return log

    def get_agent_description(self, agent_name: str) -> str:
        """Get description for each agent."""
        descriptions = {
            "ArchitectAgent": "Designs system architecture and explains design decisions",
            "CodeGenAgent": "Generates implementation code with detailed comments",
            "ReviewAgent": "Provides code review and quality assessment",
            "PolicyAgent": "Validates security and safety compliance",
            "TestAgent": "Creates comprehensive test suites and edge cases",
        }
        return descriptions.get(agent_name, "Specialized AI agent")

    def cleanup_old_exports(self, max_age_hours: int = 24):
        """Clean up old export files."""
        current_time = datetime.now()
        for filename in os.listdir(self.output_dir):
            if filename.endswith(".zip"):
                file_path = os.path.join(self.output_dir, filename)
                file_age = current_time - datetime.fromtimestamp(
                    os.path.getctime(file_path)
                )
                if file_age.total_seconds() > max_age_hours * 3600:
                    os.remove(file_path)


# Global exporter instance
exporter = CodeExporter()
