# Generated by CodeConductor v2.0 - Test Suite
# Tests for Enhanced Authentication API

import pytest
from fastapi.testclient import TestClient
from fastapi import status
import json
from auth_api_enhanced import app

client = TestClient(app)


class TestUserRegistration:
    """Test user registration functionality"""

    def test_register_valid_user(self):
        """Test successful user registration"""
        user_data = {
            "username": "testuser",
            "email": "test@example.com",
            "password": "securepassword123",
        }

        response = client.post("/register", json=user_data)
        assert response.status_code == status.HTTP_201_CREATED

        data = response.json()
        assert data["message"] == "User registered successfully"
        assert data["username"] == user_data["username"]
        assert data["email"] == user_data["email"]

    def test_register_duplicate_username(self):
        """Test registration with existing username"""
        user_data = {
            "username": "duplicateuser",
            "email": "test1@example.com",
            "password": "password123",
        }

        # First registration
        response = client.post("/register", json=user_data)
        assert response.status_code == status.HTTP_201_CREATED

        # Second registration with same username
        user_data["email"] = "test2@example.com"
        response = client.post("/register", json=user_data)
        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert "Username already registered" in response.json()["detail"]

    def test_register_duplicate_email(self):
        """Test registration with existing email"""
        user_data = {
            "username": "user1",
            "email": "duplicate@example.com",
            "password": "password123",
        }

        # First registration
        response = client.post("/register", json=user_data)
        assert response.status_code == status.HTTP_201_CREATED

        # Second registration with same email
        user_data["username"] = "user2"
        response = client.post("/register", json=user_data)
        assert response.status_code == status.HTTP_400_BAD_REQUEST
        assert "Email already registered" in response.json()["detail"]

    def test_register_invalid_email(self):
        """Test registration with invalid email format"""
        user_data = {
            "username": "testuser",
            "email": "invalid-email",
            "password": "password123",
        }

        response = client.post("/register", json=user_data)
        assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


class TestUserAuthentication:
    """Test user authentication functionality"""

    def test_login_valid_credentials(self):
        """Test successful login with valid credentials"""
        # Register user first
        user_data = {
            "username": "logintest",
            "email": "login@example.com",
            "password": "mypassword123",
        }
        client.post("/register", json=user_data)

        # Login
        login_data = {"username": "logintest", "password": "mypassword123"}

        response = client.post("/token", data=login_data)
        assert response.status_code == status.HTTP_200_OK

        data = response.json()
        assert "access_token" in data
        assert "refresh_token" in data
        assert data["token_type"] == "bearer"

    def test_login_invalid_credentials(self):
        """Test login with invalid credentials"""
        login_data = {"username": "nonexistent", "password": "wrongpassword"}

        response = client.post("/token", data=login_data)
        assert response.status_code == status.HTTP_401_UNAUTHORIZED
        assert "Incorrect username or password" in response.json()["detail"]

    def test_login_wrong_password(self):
        """Test login with correct username but wrong password"""
        # Register user first
        user_data = {
            "username": "wrongpass",
            "email": "wrongpass@example.com",
            "password": "correctpassword",
        }
        client.post("/register", json=user_data)

        # Login with wrong password
        login_data = {"username": "wrongpass", "password": "incorrectpassword"}

        response = client.post("/token", data=login_data)
        assert response.status_code == status.HTTP_401_UNAUTHORIZED
        assert "Incorrect username or password" in response.json()["detail"]


class TestTokenRefresh:
    """Test token refresh functionality"""

    def test_refresh_valid_token(self):
        """Test successful token refresh"""
        # Register and login to get tokens
        user_data = {
            "username": "refreshtest",
            "email": "refresh@example.com",
            "password": "password123",
        }
        client.post("/register", json=user_data)

        login_data = {"username": "refreshtest", "password": "password123"}
        login_response = client.post("/token", data=login_data)
        refresh_token = login_response.json()["refresh_token"]

        # Refresh token
        response = client.post("/refresh", data={"refresh_token": refresh_token})
        assert response.status_code == status.HTTP_200_OK

        data = response.json()
        assert "access_token" in data
        assert "refresh_token" in data
        assert data["token_type"] == "bearer"

    def test_refresh_invalid_token(self):
        """Test refresh with invalid token"""
        response = client.post("/refresh", data={"refresh_token": "invalid_token"})
        assert response.status_code == status.HTTP_401_UNAUTHORIZED
        assert "Invalid refresh token" in response.json()["detail"]


class TestProtectedEndpoints:
    """Test protected endpoints requiring authentication"""

    def test_get_current_user_with_valid_token(self):
        """Test accessing protected endpoint with valid token"""
        # Register and login
        user_data = {
            "username": "protectedtest",
            "email": "protected@example.com",
            "password": "password123",
        }
        client.post("/register", json=user_data)

        login_data = {"username": "protectedtest", "password": "password123"}
        login_response = client.post("/token", data=login_data)
        access_token = login_response.json()["access_token"]

        # Access protected endpoint
        headers = {"Authorization": f"Bearer {access_token}"}
        response = client.get("/users/me", headers=headers)
        assert response.status_code == status.HTTP_200_OK

        data = response.json()
        assert data["username"] == "protectedtest"
        assert data["email"] == "protected@example.com"
        assert "created_at" in data

    def test_get_current_user_without_token(self):
        """Test accessing protected endpoint without token"""
        response = client.get("/users/me")
        assert response.status_code == status.HTTP_401_UNAUTHORIZED

    def test_get_current_user_with_invalid_token(self):
        """Test accessing protected endpoint with invalid token"""
        headers = {"Authorization": "Bearer invalid_token"}
        response = client.get("/users/me", headers=headers)
        assert response.status_code == status.HTTP_401_UNAUTHORIZED


class TestHealthCheck:
    """Test health check endpoint"""

    def test_health_check(self):
        """Test health check endpoint"""
        response = client.get("/health")
        assert response.status_code == status.HTTP_200_OK

        data = response.json()
        assert data["status"] == "healthy"
        assert "timestamp" in data
        assert data["version"] == "2.0.0"


class TestLogout:
    """Test logout functionality"""

    def test_logout(self):
        """Test logout endpoint"""
        response = client.post("/logout")
        assert response.status_code == status.HTTP_200_OK
        assert response.json()["message"] == "Successfully logged out"


# Integration test
class TestFullWorkflow:
    """Test complete authentication workflow"""

    def test_complete_auth_workflow(self):
        """Test complete registration -> login -> access -> refresh workflow"""
        # 1. Register user
        user_data = {
            "username": "workflowtest",
            "email": "workflow@example.com",
            "password": "workflowpass123",
        }
        register_response = client.post("/register", json=user_data)
        assert register_response.status_code == status.HTTP_201_CREATED

        # 2. Login
        login_data = {"username": "workflowtest", "password": "workflowpass123"}
        login_response = client.post("/token", data=login_data)
        assert login_response.status_code == status.HTTP_200_OK

        tokens = login_response.json()
        access_token = tokens["access_token"]
        refresh_token = tokens["refresh_token"]

        # 3. Access protected endpoint
        headers = {"Authorization": f"Bearer {access_token}"}
        user_response = client.get("/users/me", headers=headers)
        assert user_response.status_code == status.HTTP_200_OK

        # 4. Refresh token
        refresh_response = client.post(
            "/refresh", data={"refresh_token": refresh_token}
        )
        assert refresh_response.status_code == status.HTTP_200_OK

        new_tokens = refresh_response.json()
        new_access_token = new_tokens["access_token"]

        # 5. Use new access token
        headers = {"Authorization": f"Bearer {new_access_token}"}
        user_response = client.get("/users/me", headers=headers)
        assert user_response.status_code == status.HTTP_200_OK


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
