name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    env:
      CC_TESTING_MODE: "1"
      CC_GPU_DISABLED: "1"
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          
      - name: Lint (no writes)
        run: |
          pip install ruff black
          ruff check src tests
          black --check src tests
          
      - name: Tests (mock: no GPU, no vLLM)
        run: |
          python -m pytest -q -m "not gpu and not vllm" --tb=short -ra
