name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install package in editable mode
        run: |
          pip install -e .
          
      - name: Basic import test
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -c "import codeconductor; print('✅ CodeConductor imports successfully')"
          
      - name: Run basic tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          CC_TESTING_MODE: 1
          CC_GPU_DISABLED: 1
        run: |
          python -m pytest tests/ -v --tb=short --maxfail=5 -k "not vllm and not gpu"
