name: Cursor Diagnostics (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cursor_diag:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run preflight
        run: |
          codeconductor diag cursor
      - name: Upload latest diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose-latest
          path: artifacts/diagnostics/diagnose_latest.txt

