name: Simple Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install package in editable mode
        run: |
          pip install -e .
          
      - name: Basic import test
        run: |
          python -c "import codeconductor; print('✅ CodeConductor imports successfully')"
          
      - name: Run simple tests
        env:
          CC_TESTING_MODE: 1
          CC_GPU_DISABLED: 1
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -m pytest tests/ -v --tb=short --maxfail=3 -k "not vllm and not gpu"
