name: smoke
on:
  push:
    branches: [main]
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      CC_TESTING_MODE: "1"
      CC_GPU_DISABLED: "1"
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          
      - name: Basic import test
        run: |
          python -c "import codeconductor; print('✅ CodeConductor imports successfully')"
          
      - name: Run basic tests only
        run: |
          python -m pytest -q tests/test_gpu_mock_fix.py tests/test_gpu_toggle_example.py --tb=short
