name: smoke
on:
    push:
        branches: [main]
    pull_request:
jobs:
    smoke:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .

            - name: Test import
              run: |
                  python -c "import codeconductor; print('✅ CodeConductor imports successfully')"
